version: '3.4'

services:
  grpcgreeterserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  grpcgreeterclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_SERVER_URL=http://grpcgreeter-grpcgreeterserver-1